### PR TITLE
Add definition for push and fetch

### PR DESCRIPTION
**Pull request by danielkcole**
Added a definition for git push and fetch

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Which issue does this resolve?

**Comment by danielkcole** [comment]
resolves #13

**Comment by StoneyJackson** [comment]
Edit the body of the PR

**Comment by danielkcole** [comment]
resolves #22

**Comment by StoneyJackson** [comment]
Resolve conflicts.

**Comment by danielkcole** [comment]
resolves #22

**Pull request merged**
